export EDITOR='subl -w'
export JAVA_HOME='/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home'
export CC='/Applications/Xcode.app/Contents/Developer/usr/bin/gcc'
export DYLD_LIBRARY_PATH='/usr/local/mysql/lib:$DYLD_LIBRARY_PATH'
export PATH="$HOME/.local/bin:$HOME/.rbenv/bin:$HOME/perl5/perlbrew/bin:$PATH"
export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/opt/openssl/lib/"
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
export DISABLE_SPRING=1
