export CC='/Applications/Xcode.app/Contents/Developer/usr/bin/gcc'
export DISABLE_SPRING=1
export DYLD_LIBRARY_PATH="/usr/local/mysql/lib:$DYLD_LIBRARY_PATH"
export EDITOR='subl -w'
export JAVA_HOME='/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home'
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
export LIBRARY_PATH="/usr/local/opt/openssl/lib:$LIBRARY_PATH"
export RAILS_MAX_THREADS=5
export RAILS_MIN_THREADS=5
